# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: UseDotNet@2
    inputs:
      version: '3.1.x'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/LegoSharpTest/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - publish: $(System.DefaultWorkingDirectory)/LegoSharp/bin/Release
    artifact: Release
